# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

output: 'prefixed'

includes:
  app:
    taskfile: ./taskfiles/back.yml
    aliases: [back, b]
  frontend:
    taskfile: ./taskfiles/frontend.yml
    aliases: [frontend, f]

tasks:
  dev:
    desc: Run app in dev mode
    deps: [f:build]
    cmds:
      - task b:dev
    silent: true
